"""monthly-limited prize columns for fortune wheel

Adds the schema needed for time-windowed and capped wheel prizes —
e.g. "one winner per calendar month", "prize only available days
1–7". This migration is schema-only; the routing and reset logic
ships in a follow-up.

Schema changes:

* ``wheel_prizes.monthly_limit`` — max wins per month, NULL = unlimited.
* ``wheel_prizes.monthly_wins_count`` — running counter, reset by the
  application when ``last_reset_month`` rolls over. Default 0.
* ``wheel_prizes.window_start_day`` / ``window_end_day`` — calendar-day
  availability window (1–28 to dodge month-length edge cases). NULL
  on both ends means always available.
* ``wheel_prizes.current_month_winner`` — masked username of the
  current cycle's winner, shown in UI as "already claimed by …".
* ``wheel_prizes.last_reset_month`` — month number (1–12) when the
  counters were last zeroed. Compared against now() at spin time to
  detect rollover.

* ``wheel_spins.spin_nonce`` — per-spin UUID, UNIQUE. Generated by the
  client before the spin RPC and replayed back; the unique constraint
  is the structural backstop against double-spin from retried or
  duplicated requests.

Revision ID: 0087
Revises: 0086
Create Date: 2026-05-19

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '0087'
down_revision: Union[str, None] = '0086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'wheel_prizes',
        sa.Column('monthly_limit', sa.Integer(), nullable=True),
    )
    op.add_column(
        'wheel_prizes',
        sa.Column(
            'monthly_wins_count',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )
    op.add_column(
        'wheel_prizes',
        sa.Column('window_start_day', sa.Integer(), nullable=True),
    )
    op.add_column(
        'wheel_prizes',
        sa.Column('window_end_day', sa.Integer(), nullable=True),
    )
    op.add_column(
        'wheel_prizes',
        sa.Column('current_month_winner', sa.String(length=100), nullable=True),
    )
    op.add_column(
        'wheel_prizes',
        sa.Column('last_reset_month', sa.Integer(), nullable=True),
    )

    op.add_column(
        'wheel_spins',
        sa.Column('spin_nonce', sa.String(length=36), nullable=True),
    )
    op.create_unique_constraint(
        'uq_wheel_spins_spin_nonce',
        'wheel_spins',
        ['spin_nonce'],
    )


def downgrade() -> None:
    op.drop_constraint('uq_wheel_spins_spin_nonce', 'wheel_spins', type_='unique')
    op.drop_column('wheel_spins', 'spin_nonce')

    op.drop_column('wheel_prizes', 'last_reset_month')
    op.drop_column('wheel_prizes', 'current_month_winner')
    op.drop_column('wheel_prizes', 'window_end_day')
    op.drop_column('wheel_prizes', 'window_start_day')
    op.drop_column('wheel_prizes', 'monthly_wins_count')
    op.drop_column('wheel_prizes', 'monthly_limit')
